### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by ss-remygreinhofer** [NerdWalletOSS/terraformpy#51]
I am not able to install `terraformpy`, from the PyPI. The `VERSION` file seems to be missing somehow.

Repro steps:
```bash
mkdir terraformpy-test-project
cd terraformpy-test-project
python3 -m venv venv
source venv/bin/activate
pip install -U pip pipenv
```

With `pipenv`:
```
$ pipenv install --two terraformpyCourtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a Pipfile for this project…
Installing terraformpy…
Adding terraformpy to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (2a539d)!
Installing dependencies from Pipfile.lock (2a539d)…
An error occurred while installing terraformpy==1.1.2 --hash=sha256:338060801a421948566ad5d679d0b7e9ce23fd88fd38fef5cde6b700680d8de9 --hash=sha256:90376ba65649ecb57f081b0e4709ccad4c9fae5adff3f8db0b97eb064fa6916a! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:00
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting terraformpy==1.1.2', '  Using cached https://files.pythonhosted.org/packages/21/da/a7a50f082273c7edf922e5e7e66133f8d789087b718942646866d8b10b0e/terraformpy-1.1.2.tar.gz']
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '     command: /Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/bin/python3 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-y1w66lgp/terraformpy/setup.py\'"\'"\'; __file__=\'"\'"\'/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-y1w66lgp/terraformpy/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-y1w66lgp/terraformpy/pip-egg-info', '         cwd: /private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-y1w66lgp/terraformpy/', '    Complete output (5 lines):', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-y1w66lgp/terraformpy/setup.py", line 7, in <module>', "        with open('VERSION') as version_fd:", "    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 —
```

Same error with `pip`:
```
$ pip install terraformpy
[...]
    ERROR: Command errored out with exit status 1:
     command: /Users/remygreinhofer/remy-project/labs/terraformpy-test-project/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-j_q7fk5q/terraformpy/setup.py'"'"'; __file__='"'"'/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-j_q7fk5q/terraformpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-j_q7fk5q/terraformpy/pip-egg-info
         cwd: /private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-j_q7fk5q/terraformpy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nc/5sdcykxd01x_pkjyh0dkvgpr0000gp/T/pip-install-j_q7fk5q/terraformpy/setup.py", line 7, in <module>
        with open('VERSION') as version_fd:
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

A workaround consisted in installing `terraformpy` from source, using `pip install -e .`.

**Comment by borgstrom** [comment]
This is now fixed in terraformpy==1.1.3

Thanks for the report, and sorry for the inconvenience!
